name: Create docker image

on:
  create:  # Keep existing trigger
  workflow_dispatch:  # Add manual trigger
    inputs:
      base_path:
        description: 'Base path for the application (e.g., /umami)'
        required: false
        default: '/umami'
        type: string

jobs:
  build:
    name: Build, push, and deploy
    if: ${{ startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        db-type: [postgresql]

    steps:
      - uses: actions/checkout@v3

      - name: Set env
        run: |
          echo "NOW=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Generate tags
        id: generate_tags
        run: |
          echo "tag_patch=$(echo ${{ matrix.db-type }})-${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "tag_minor=$(echo ${{ matrix.db-type }})-$(echo ${GITHUB_REF#refs/tags/} | cut -d. -f1,2)" >> $GITHUB_ENV
          echo "tag_major=$(echo ${{ matrix.db-type }})-$(echo ${GITHUB_REF#refs/tags/} | cut -d. -f1)" >> $GITHUB_ENV
          echo "tag_latest=$(echo ${{ matrix.db-type }})-latest" >> $GITHUB_ENV

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image to ghcr.io for ${{ matrix.db-type }}
        with:
          image: umami
          tags: ${{ env.tag_major }}, ${{ env.tag_minor }}, ${{ env.tag_patch }}, ${{ env.tag_latest }}
          buildArgs: |
            DATABASE_TYPE=${{ matrix.db-type }}
            BASE_PATH=${{ github.event.inputs.base_path || '/umami' }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}